### ISSUE TITLE
About multi-scale VectorQuantizer structure.

### ISSUE THREAD

**Issue by yjzhang96** [chaofengc/FeMaSR#6]
I noticed that in `quant_arch.py`, the code can be expand to multi-scale VectorQuantizer in a cascade manner (as long as you provide multiple codebook params in the configs). Though the model you provide did not make use of this structure, I am curious about whether you have conduct experiments about this structure, or whether there is any literature about it. I'd like to get some insight about this structure, thank you for your help!

**Comment by chaofengc** [comment]
Yes, we tried the multi-scale vqvae, i.e., vqvae2, for several weeks, but hardly made it work. The problem was that the feature matching seems to be much more difficult with low level codebooks. We did not find good solutions to that. As far as I know, there are few works about multi-scale vqvae, maybe there's room to explore, or maybe it simply doesn't work. A recent related paper is [residual vqgan](https://github.com/kakaobrain/rq-vae-transformer). You may also be interested.

Hope you can have new findings.

**Comment by yjzhang96** [comment]
Thank you for your reply, which helps a lot!
